name: "GitHub Docker Action"
description: "Build and publish your repository as a Docker image and push it to GitHub Package Registry in one step"
inputs:
  accessToken:
    description: "GitHub Repository Token to log in using."
    required: true
  context:
    description: "Where should GitHub Docker find the Dockerfile, relative to the root of the repository."
    required: false
    default: "."
  username:
    description: "GitHub user to publish the image on behalf of."
    required: false
  repositoryName:
    description: "The repository to push the image to. Defaults to current repository. Must be specified in format user/repo"
    required: false
  imageName:
    description: "The desired name for the image. Defaults to current repository name."
    required: false
  imageTag:
    description: "The desired tag for the image. Defaults to current branch or release version number."
    required: false
  buildArguments:
    description: "The build arguments for image."
    required: false
outputs:
  imageURL:
    description: "The URL of the image."
runs:
  using: "node12"
  main: "dist/index.js"
branding:
  icon: "anchor"
  color: "blue"
